version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "127.0.0.1:9200:9200"  # Map Public IP
      - "10.0.0.143:9200:9200"    # Map Private IP
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic-net

volumes:
  data01:
    driver: local

networks:
  elastic-net:

